name: pcp
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - ffmpeg
  - pip
  - pip:
    - -e .
    - easyocr
    - opencv-python
    - babelfish
    - pgsrip
    - numpy
    - torch

